global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'seckill-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'order-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081'] # 假设 order-service 运行在 8081